# ESTE ARQUIVO TEM COMO FINALIDADE GUARDAR AS CONSTANTES UTILIZADAS PELOS SCRIPTS R.

###### VOTAÇÕES NOMINAIS POR MUNICIPIO E ZONA ###### 
# Nomes das colunas da tabela dos candidatos com munzonas


# Até o ano de 2012
col_names_candidatos_munzona_ate_2012 <- tolower(c("DATA_GERACAO", 
                                                   "HORA_GERACAO",
                                                   "ANO_ELEICAO", 
                                                   "NUM_TURNO",
                                                   "DESCRICAO_ELEICAO", 
                                                   "SIGLA_UF", 
                                                   "SIGLA_UE", 
                                                   "CODIGO_MUNICIPIO",
                                                   "NOME_MUNICIPIO", 
                                                   "NUMERO_ZONA", 
                                                   "CODIGO_CARGO", 
                                                   "NUMERO_CAND",
                                                   "SQ_CANDIDATO", 
                                                   "NOME_CANDIDATO", 
                                                   "NOME_URNA_CANDIDATO", 
                                                   "DESCRICAO_CARGO",
                                                   "COD_SIT_CAND_SUPERIOR", 
                                                   "DESC_SIT_CAND_SUPERIOR", 
                                                   "CODIGO_SIT_CANDIDATO", 
                                                   "DESC_SIT_CANDIDATO",
                                                   "CODIGO_SIT_CAND_TOT", 
                                                   "DESC_SIT_CAND_TOT", 
                                                   "NUMERO_PARTIDO", 
                                                   "SIGLA_PARTIDO",
                                                   "NOME_PARTIDO", 
                                                   "SEQUENCIAL_LEGENDA", 
                                                   "NOME_COLIGACAO", 
                                                   "COMPOSICAO_LEGENDA",
                                                   "TOT_VOTOS"))

# A partir do ano de 2014
col_names_candidatos_munzona_2014_em_diante <- tolower(c("DATA_GERACAO", 
                                                        "HORA_GERACAO",
                                                        "ANO_ELEICAO", 
                                                        "NUM_TURNO",
                                                        "DESCRICAO_ELEICAO", 
                                                        "SIGLA_UF", 
                                                        "SIGLA_UE", 
                                                        "CODIGO_MUNICIPIO",
                                                        "NOME_MUNICIPIO", 
                                                        "NUMERO_ZONA", 
                                                        "CODIGO_CARGO", 
                                                        "NUMERO_CAND",
                                                        "SQ_CANDIDATO", 
                                                        "NOME_CANDIDATO", 
                                                        "NOME_URNA_CANDIDATO", 
                                                        "DESCRICAO_CARGO",
                                                        "COD_SIT_CAND_SUPERIOR", 
                                                        "DESC_SIT_CAND_SUPERIOR", 
                                                        "CODIGO_SIT_CANDIDATO", 
                                                        "DESC_SIT_CANDIDATO",
                                                        "CODIGO_SIT_CAND_TOT", 
                                                        "DESC_SIT_CAND_TOT", 
                                                        "NUMERO_PARTIDO", 
                                                        "SIGLA_PARTIDO",
                                                        "NOME_PARTIDO", 
                                                        "SEQUENCIAL_LEGENDA", 
                                                        "NOME_COLIGACAO", 
                                                        "COMPOSICAO_LEGENDA",
                                                        "TOT_VOTOS", 
                                                        "TRANSITO"))


###### CANDIDATOS ###### 
# Nomes das colunas da tabela dos candidatos

# Até o ano de 2010
col_names_candidatos_ate_2010 <- tolower(c(
                                       "DATA_GERACAO", 
                                       "HORA_GERACAO", 
                                       "ANO_ELEICAO",
                                       "NUM_TURNO", 
                                       "DESCRICAO_ELEICAO", 
                                       "SIGLA_UF",
                                       "COD_CIDADE", 
                                       "NOME_MUNICIPIO", 
                                       "COD_CARGO", 
                                       "DESCRICAO_CARGO", 
                                       "NOME_CANDIDATO",
                                       "SEQUENCIAL_CANDIDATO", 
                                       "NUMERO_CAND",
                                       "CPF_CANDIDATO", 
                                       "NOME_URNA_CANDIDATO",
                                       "COD_SIT_CANDIDATURA", 
                                       "DESC_SIT_CANDIDATO", 
                                       "NUMERO_PARTIDO", 
                                       "SIGLA_PARTIDO",
                                       "NOME_PARTIDO", 
                                       "CODIGO_LEGENDA",
                                       "SIGLA_LEGENDA",
                                       "COMPOSICAO_LEGENDA", 
                                       "NOME_COLIGACAO", 
                                       "CODIGO_OCUPACAO",
                                       "DESCRICAO_OCUPACAO", 
                                       "DATA_NASCIMENTO", 
                                       "NUM_TIT_ELEITORAL_CANDIDATO",
                                       "IDADE_DATA_CANDIDATO", 
                                       "COD_SEXO", 
                                       "SEXO", 
                                       "COD_GRAU_INSTRUCAO",
                                       "GRAU_INSTRUCAO", 
                                       "COD_ESTADO_CIVIL", 
                                       "ESTADO_CIVIL",
                                       "CODIGO_NACIONALIDADE",
                                       "DESCRICAO_NACIONALIDADE", 
                                       "SIGLA_UF_NASCIMENTO",
                                       "COD_MUNICIPIO_NASCIMENTO", 
                                       "NOME_MUNICIPIO_NASCIMENTO",
                                       "DESPESA_MAX_CAMPANHA", 
                                       "COD_SIT_TOT_TURNO",
                                       "DESC_SIT_CAND_TOT"))

# No ano de 2012
col_names_candidatos_2012 <- tolower(c("DATA_GERACAO", 
                                       "HORA_GERACAO", 
                                       "ANO_ELEICAO",
                                       "NUM_TURNO", 
                                       "DESCRICAO_ELEICAO", 
                                       "SIGLA_UF",
                                       "COD_CIDADE", 
                                       "NOME_MUNICIPIO", 
                                       "COD_CARGO", 
                                       "DESCRICAO_CARGO", 
                                       "NOME_CANDIDATO",
                                       "SEQUENCIAL_CANDIDATO", 
                                       "NUMERO_CAND",
                                       "CPF_CANDIDATO", 
                                       "NOME_URNA_CANDIDATO",
                                       "COD_SIT_CANDIDATURA", 
                                       "DESC_SIT_CANDIDATO", 
                                       "NUMERO_PARTIDO", 
                                       "SIGLA_PARTIDO",
                                       "NOME_PARTIDO", 
                                       "CODIGO_LEGENDA",
                                       "SIGLA_LEGENDA",
                                       "COMPOSICAO_LEGENDA", 
                                       "NOME_COLIGACAO", 
                                       "CODIGO_OCUPACAO",
                                       "DESCRICAO_OCUPACAO", 
                                       "DATA_NASCIMENTO", 
                                       "NUM_TIT_ELEITORAL_CANDIDATO",
                                       "IDADE_DATA_CANDIDATO", 
                                       "COD_SEXO", 
                                       "SEXO", 
                                       "COD_GRAU_INSTRUCAO",
                                       "GRAU_INSTRUCAO", 
                                       "COD_ESTADO_CIVIL", 
                                       "ESTADO_CIVIL",
                                       "CODIGO_NACIONALIDADE",
                                       "DESCRICAO_NACIONALIDADE", 
                                       "SIGLA_UF_NASCIMENTO",
                                       "COD_MUNICIPIO_NASCIMENTO", 
                                       "NOME_MUNICIPIO_NASCIMENTO",
                                       "DESPESA_MAX_CAMPANHA", 
                                       "COD_SIT_TOT_TURNO",
                                       "DESC_SIT_CAND_TOT", 
                                       "EMAIL"))

# A partir de 2014
col_names_candidatos_2014_em_diante <- tolower(c("DATA_GERACAO", 
                                  "HORA_GERACAO", 
                                  "ANO_ELEICAO",
                                  "NUM_TURNO", 
                                  "DESCRICAO_ELEICAO", 
                                  "SIGLA_UF",
                                  "COD_CIDADE", 
                                  "NOME_MUNICIPIO", 
                                  "COD_CARGO", 
                                  "DESCRICAO_CARGO", 
                                  "NOME_CANDIDATO",
                                  "SEQUENCIAL_CANDIDATO", 
                                  "NUMERO_CAND",
                                  "CPF_CANDIDATO", 
                                  "NOME_URNA_CANDIDATO",
                                  "COD_SIT_CANDIDATURA", 
                                  "DESC_SIT_CANDIDATO", 
                                  "NUMERO_PARTIDO", 
                                  "SIGLA_PARTIDO",
                                  "NOME_PARTIDO", 
                                  "CODIGO_LEGENDA",
                                  "SIGLA_LEGENDA",
                                  "COMPOSICAO_LEGENDA", 
                                  "NOME_COLIGACAO", 
                                  "CODIGO_OCUPACAO",
                                  "DESCRICAO_OCUPACAO", 
                                  "DATA_NASCIMENTO", 
                                  "NUM_TIT_ELEITORAL_CANDIDATO",
                                  "IDADE_DATA_CANDIDATO", 
                                  "COD_SEXO", 
                                  "SEXO", 
                                  "COD_GRAU_INSTRUCAO",
                                  "GRAU_INSTRUCAO", 
                                  "COD_ESTADO_CIVIL", 
                                  "ESTADO_CIVIL",
                                  "COD_COR_RACA", 
                                  "COR_RACA", 
                                  "CODIGO_NACIONALIDADE",
                                  "DESCRICAO_NACIONALIDADE", 
                                  "SIGLA_UF_NASCIMENTO",
                                  "COD_MUNICIPIO_NASCIMENTO", 
                                  "NOME_MUNICIPIO_NASCIMENTO",
                                  "DESPESA_MAX_CAMPANHA", 
                                  "COD_SIT_TOT_TURNO",
                                  "DESC_SIT_CAND_TOT", 
                                  "EMAIL"))


